"""
BS Allied Health Sciences - 2nd Semester Syllabus
Topics organized by subject, taken from the official curriculum (PMS-607/608/609).
Used by app.py to build the dropdown menus.
"""

SYLLABUS = {
    "Physiology": {
        "Nervous System": [
            "Nervous system introduction",
            "Action potential and resting membrane potential",
            "Neuron structure and classification",
            "Meninges, CSF and ventricles",
            "Neuroglia",
            "Receptors",
            "Synapse",
            "Neurotransmitters and neuromodulators",
            "Reflex activity and reflex arc",
            "Cranial and spinal nerves",
            "Somatic system (somatosensory and somatomotor)",
            "Autonomic nervous system (sympathetic and parasympathetic)",
            "Physiology of pain",
        ],
        "Special Senses": [
            "Sense of vision (eye structure and visual pathway)",
            "Sense of hearing (ear and auditory pathway)",
            "Sense of taste (taste buds)",
            "Sense of smell (olfaction)",
        ],
        "Blood Physiology": [
            "Body fluids and compartments",
            "Blood plasma composition and functions",
            "Hematopoiesis, erythropoiesis, leukopoiesis, thrombopoiesis",
            "Red blood cells (RBC)",
            "Hemoglobin structure",
            "White blood cells (WBC)",
            "Homeostasis and coagulation",
            "Blood groups (ABO and Rh factor)",
        ],
        "Cardiovascular System": [
            "Introduction to CVS (arterial and venous system)",
            "Physiology of heart (structure and action)",
            "Cardiac muscle properties",
            "Cardiac cycle",
            "Heart sounds",
            "Cardiac output, stroke volume, heart rate",
            "Blood pressure and its regulation",
            "Conductive system of heart",
            "ECG (electrocardiography)",
            "Systemic, pulmonary and capillary circulation",
        ],
        "Lymphatic System": [
            "Lymphatic system and lymph nodes",
            "Formation and composition of lymph",
            "Spleen (red pulp and white pulp)",
            "Thymus",
        ],
        "Immune System": [
            "Immunity (innate and acquired)",
            "Mechanism of innate and acquired immunity",
            "Antigen and antibody",
            "Cell mediated and humoral immunity",
            "Immunization",
        ],
    },

    "Biochemistry": {
        "Metabolism Basics": [
            "Definition and types of metabolism",
        ],
        "Carbohydrate Metabolism": [
            "Glycolysis",
            "Glycogenolysis",
            "Pentose phosphate pathway",
            "Rapoport-Luebering shunt (glycolysis in RBC)",
            "Krebs cycle (citric acid cycle)",
            "Electron transport chain",
            "Cori cycle",
            "Gluconeogenesis",
            "Glycogenesis",
            "Regulation of carbohydrate metabolism",
            "ATP calculation from glucose",
        ],
        "Protein and Amino Acid Metabolism": [
            "Metabolic pathways of amino acids",
            "Ammonia synthesis and excretion",
            "Urea cycle",
        ],
        "Lipid Metabolism": [
            "Oxidation of fatty acids",
            "Beta oxidation of lipids",
            "Steps of beta oxidation",
            "ATP calculation from fatty acids",
        ],
        "Nucleotide Metabolism": [
            "De novo and salvage pathways of nucleotide synthesis",
            "Catabolism of purines",
            "Purine catabolism",
            "Uric acid synthesis and elimination",
        ],
        "Nutrition": [
            "Nutrients and nutrition",
            "Essential nutrient groups",
            "Balanced diet",
            "Nutritional value of biomolecules",
            "Eating disorders (anorexia, obesity)",
            "Malnutrition (Kwashiorkor, Marasmus)",
        ],
        "Clinical Enzymology": [
            "Clinical / diagnostic enzymology",
            "Factors affecting enzyme activity",
            "Clinical significance of enzymes (ALT, AST, ALP, GGT, LDH, CK, Lipase, Amylase)",
        ],
    },

    "Anatomy": {
        "Skull Bones / Scalp": [
            "Scalp (layers, vascular and nerve supply)",
            "Skull bones and sutures",
            "Frontal, occipital, maxilla, sphenoid, temporal bones",
            "Foetal skull and hyoid bone",
            "Cranial cavity",
            "Meninges",
        ],
        "Brain and Nerves": [
            "Structure and parts of brain",
            "Vascular and nerve supply of brain",
            "Cerebrospinal fluid (CSF) and ventricles",
            "Cranial nerves",
            "Spinal cord and spinal nerves",
        ],
        "Face and Oral Cavity": [
            "Face (bones, muscles, vascular and nerve supply)",
            "Temporomandibular joint",
            "Sinuses",
            "Orbit and eye",
            "Lacrimal apparatus and gland",
            "Teeth",
            "Ear (external, middle, internal)",
            "Palate",
            "Pharynx",
            "Tonsils and auditory tube",
            "Larynx",
        ],
        "Neck": [
            "Neck bones and vertebrae",
            "Suboccipital triangle",
            "Deep cervical fascia and carotid sheath",
            "Anterior and posterior triangle of neck",
            "Sternocleidomastoid muscle",
            "Supra and infra hyoid muscles",
            "Cervical plexus",
        ],
        "Glands": [
            "Parotid and sublingual gland",
            "Submandibular gland",
            "Thyroid gland",
            "Parathyroid gland",
        ],
        "Upper Limb": [
            "Pectoral region and axilla",
            "Shoulder girdle",
            "Arm and upper arm (bones, joints, blood and nerve supply)",
            "Muscles of upper limb, rotator cuff, cubital fossa",
            "Forearm and hand",
            "Vessels, nerves, lymphatics of upper limb",
        ],
        "Lower Limb": [
            "Gluteal region",
            "Thigh, popliteal fossa and muscles",
            "Leg and foot",
            "Muscles and joints of lower limb",
            "Vessels, nerves, lymphatics of lower limb",
        ],
    },
"English": {
        "Paragraph Writing": [
            "Structural components of a paragraph",
            "Free writing and pre-writing strategies",
            "Arranging sentences in logical order",
            "Using transitions for smooth flow of ideas",
            "Appropriate form of verbs in a paragraph",
            "Writing a unified and coherent paragraph",
            "Meanings of words in a paragraph",
        ],
        "Essay Writing": [
            "Basics of writing an essay",
            "Prewriting stage",
            "Writing stage of an essay",
            "Writing essays on different topics",
        ],
        "CV and Job Application": [
            "Basics of making a curriculum vitae (CV)",
            "Components of writing an application",
            "Language and sentences of an application",
            "Writing an application for a job",
            "Translating an application (English to Urdu)",
        ],
        "Study Skills": [
            "Skimming and scanning",
            "Intensive and extensive reading",
            "Speed reading",
            "Identifying main ideas and supporting detail",
            "Extracting themes from a text",
            "Summary and precise writing",
        ],
        "Academic Skills": [
            "Basics of writing a letter",
            "Writing clear and courteous letters of request",
            "Salutation in a letter or memo",
            "Persuasive letter writing",
            "Writing a clear and concise memo",
            "Minutes of a meeting",
            "Use of digital library and internet",
        ],
        "Presentation Skills": [
            "Elements of a good presentation",
            "Well organized and clear presentation",
            "Purpose and audience of a presentation",
            "Clarity and accuracy in presenting",
            "Handling questions from the audience",
            "Emphasis on content, style and pronunciation",
        ],
    },
}
